baseurl: officialsite/
url: "geovannycordero.github.io/"
permalink: /:title

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"
